<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.7" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
        <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Template.Application\Template.Application.csproj" />
        <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="SqlScripts/*" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="DataAccess\EntityConfigurations" />
      <Folder Include="SqlScripts" />
    </ItemGroup>
    
</Project>
